FROM fschlatt/natural-language-processing-exercises:0.0.1

COPY preprocessing.py /code/preprocessing.py
COPY run.py /code/run.py
COPY model.joblib /code/model.joblib

ENTRYPOINT [ "python3", "/code/run.py" ]


